language: node_js
dist: xenial

branches:
    only:
    - master

stages:
    - test
    - ':build: and :push:'

jobs:
    include:
    - stage: test
      script: bash ./scripts/build.test.image.sh
    - stage: ':build: and :push:'
      script: ./scripts/docker.build.push.sh
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: njs-deploy-travis
        on: master
