language: node_js
node_js:
    - lts/*
dist: xenial

services:
    - docker

branches:
    only:
    - master

if: branch = master and commit_message =~ /:ship:/

install:
    - npm install -g heroku
    - npm install

stages:
    - test
    - ':build: and :push:'

jobs:
    include:
    - stage: test
      script: bash ./scripts/build.test.image.sh
    - stage: ':build: and :push:'
      script: 
        - bash ./scripts/docker.build.push.sh
        - heroku container:release web -a njs-deploy-travis
