FROM alpine:latest

COPY docker/entry.install.sh /tmp/entry.install.sh
COPY docker/entry.run.sh /tmp/entry.run.sh

RUN chmod +x /tmp/entry.install.sh \
 && chmod +x /tmp/entry.run.sh

RUN /tmp/entry.install.sh

ENTRYPOINT [ "/tmp/entry.run.sh" ]